{% set version = "2.0.12" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-rxode2ll
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/rxode2ll_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/rxode2ll/rxode2ll_{{ version }}.tar.gz
  sha256: 5bb093a1c7d3e651175c9881266b35216baecc1f9f6831adb5317271085dd5a3

build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
  missing_dso_whitelist:
    - '*/R.dll'           # [win]
    - '*/tbb.dll'         # [win]

requirements:
  build:
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
    - {{ compiler('c') }}          # [not win]
    - {{ stdlib('c') }}
    - {{ compiler('m2w64_c') }}    # [win]
    - {{ compiler('cxx') }}        # [not win]
    - {{ compiler('m2w64_cxx') }}  # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}sed               # [win]
    - {{ posix }}grep              # [win]
    - {{ posix }}autoconf
    - {{ posix }}automake          # [not win]
    - {{ posix }}automake-wrapper  # [win]
    - pkg-config
    - {{ posix }}make
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-bh >=1.78.0.0
    - r-rcpp >=1.0.8
    - r-rcppeigen >=0.3.3.9.2
    - r-rcppparallel
    - r-stanheaders >=2.21.0.7
    - r-checkmate
  run:
    - r-base
    - r-bh >=1.78.0.0
    - r-rcpp >=1.0.8
    - r-rcppeigen >=0.3.3.9.2
    - r-rcppparallel
    - r-stanheaders >=2.21.0.7
    - r-checkmate

test:
  commands:
    - $R -e "library('rxode2ll')"           # [not win]
    - "\"%R%\" -e \"library('rxode2ll')\""  # [win]

about:
  home: https://nlmixr2.github.io/rxode2ll/
  dev_url: https://github.com/nlmixr2/rxode2ll/
  license: GPL-3.0-or-later
  summary: Provides the log-likelihoods with gradients from 'stan' (Carpenter et al (2015), <arXiv:1509.07164>) needed for generalized log-likelihood estimation in 'nlmixr2' (Fidler et al (2019) <doi:10.1002/psp4.12445>). This is split of to reduce computational burden of recompiling 'rxode2' (Wang, Hallow and James (2016)
    <doi:10.1002/psp4.12052>) which runs the 'nlmixr2' models during estimation.
  license_family: GPL3
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: rxode2ll
# Version: 2.0.11
# Title: Log-Likelihood Functions for 'rxode2'
# Authors@R: c( person("Matthew L.","Fidler", role = c("aut", "cre"), email = "matthew.fidler@gmail.com", comment=c(ORCID="0000-0001-8538-6691")))
# Maintainer: Matthew L. Fidler <matthew.fidler@gmail.com>
# Depends: R (>= 4.0.0)
# Suggests: covr, testthat (>= 3.0.0)
# Imports: Rcpp (>= 1.0.8), checkmate, RcppParallel
# Description: Provides the log-likelihoods with gradients from 'stan' (Carpenter et al (2015), <arXiv:1509.07164>) needed for generalized log-likelihood estimation in 'nlmixr2' (Fidler et al (2019) <doi:10.1002/psp4.12445>). This is split of to reduce computational burden of recompiling 'rxode2' (Wang, Hallow and James (2016) <doi:10.1002/psp4.12052>) which runs the 'nlmixr2' models during estimation.
# BugReports: https://github.com/nlmixr2/rxode2ll/issues/
# NeedsCompilation: yes
# License: GPL (>= 3)
# URL: https://nlmixr2.github.io/rxode2ll/, https://github.com/nlmixr2/rxode2ll/
# RoxygenNote: 7.2.3
# Biarch: true
# LinkingTo: Rcpp (>= 1.0.8), RcppEigen (>= 0.3.3.9.2), StanHeaders (>= 2.21.0.7), BH (>= 1.78.0.0), RcppParallel
# Encoding: UTF-8
# Language: en-US
# Config/testthat/edition: 3
# Packaged: 2023-03-17 17:09:38 UTC; matt
# Author: Matthew L. Fidler [aut, cre] (<https://orcid.org/0000-0001-8538-6691>)
# Repository: CRAN
# Date/Publication: 2023-03-17 23:40:02 UTC
